// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slqdicomlbuhacmukbov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscWRpY29tbGJ1aGFjbXVrYm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTQzNzksImV4cCI6MjA2NDg3MDM3OX0.mCAK_F7C8IvJT2D_8kP25pIUrnjSNS5WljT9ES_ZD3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);